apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sip-api
  template:
    metadata:
      labels:
        app: sip-api
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/CONTAINER_IMAGE_NAME
          imagePullPolicy: Always