server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    url: jdbc:postgresql://sip-db-service.default.svc.cluster.local:5432/postgres?user=sip&password=sip.2022

    username: '{db-username}'
    password: '{db-password}'
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: sip.2022.unlu@gmail.com
    password: '{smtp-password}'
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

jwt-secret: '{jwt-secret}'
jwt-issuer: '{jwt-issuer}'
jwt-expiration-days: '{jwt-expiration-days}'

superadmin-email: '{admin-email}'
superadmin-password: '{admin-password}'

heroku-url: 'https://sip-api-dev.herokuapp.com'