spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  datasource:
    url: jdbc:postgresql://localhost:5050/sip
    username: sip
    password: sip.2022
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
