server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
#    url: jdbc:postgresql://sip-db-service.default.svc.cluster.local:5432/sip?user=sip&password=sip.2022
    url: jdbc:postgresql://localhost:5050/sip
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: false
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sip.2022.unlu@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expirationDays: ${JWT_EXPIRATION_DAYS}

superadmin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

app:
  url: ${APPLICATION_URL}
