spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    username: hub
    password: hub.2020
    driver-class-name: org.h2.Driver

  flyway:
    baseline-on-migrate: true
    enabled: true
    out-of-order: true