spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
    username: sip
    password: sip.2022
    driver-class-name: org.h2.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: sip.2022.unlu@gmail.com
    password: xudijuocjkxwkgdo
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

jwt-secret: placeholder
jwt-issuer: placeholder
jwt-expiration-days: 5

superadmin-email: admin@admin.com
superadmin-password: adminadmin
app-url: 'localhost:8080'