spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

  datasource:
    url: jdbc:postgresql://ec2-3-225-213-67.compute-1.amazonaws.com/d7sshocjgndia3
    username: tdbsqzqgpeflnv
    password: 56439dc99c665eed0beca15d7c2cce26fc3468fd5753ab61e822e7947a96b73a
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
