server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5050/sip
    username: sip
    password: sip.2022
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false
