server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

# Set environment vars of the Heroku deployed Database
  datasource:
    url: jdbc:postgresql://localhost:5050/sip
    username: sip
    password: sip.2022
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: true
