server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sip.2022.unlu@gmail.com
    password: xudijuocjkxwkgdo
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  datasource:
    url: jdbc:postgresql://localhost:5050/sip
    username: sip
    password: sip.2022
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    out-of-order: true
    enabled: false

jwt-secret: '{jwt-secret}'
jwt-issuer: '{jwt-issuer}'
jwt-expiration-days: '{jwt-expiration-days}'

superadmin-email: 'superadmin@admin.com'
superadmin-password: 'supersecretpassword'
heroku-url: 'localhost:8080'

communication:
  from: no-reply@sip2022.inc

