apiVersion: apps/v1
kind: Deployment
metadata:
  name: sip-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: sip-db
  template:
    metadata:
      labels:
        app: sip-db
    spec:
      containers:
        - name: sip-db
          image: postgres:10
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "4Gi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sip.2022
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: sip-postgres-pvc