apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sip-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sip-postgres-pvc
spec:
  # must match namespace name
  storageClassName: sip-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 500Mi