kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sip-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sip-postgres-pv
spec:
  # must match namespace name
  storageClassName: sip-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi