apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sip-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sip-postgres-pv
spec:
  # must match namespace name
  storageClassName: sip-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi