apiVersion: v1
kind: Service
# default namespace
metadata:
  name: sip-db-service
spec:
  type: ClusterIP
  selector:
    # must match with deployment identifier
    app: sip-db
  ports:
    - protocol: TCP
      # external port
      port: 5432
      # internal port
      targetPort: 5432
