apiVersion: v1
kind: ConfigMap
# identifier
metadata:
  name: sip-api-configmap
  namespace: default
  labels:
    app: sip-api # Must match with api deployment identifier
data:
  JWT_SECRET: supersecretkey
  JWT_ISSUER: NC-SIP-2022
  JWT_EXPIRATION_DAYS: "5"
  DB_PORT: "5432"
  DB_NAME: sip
  DB_USER: sip
  DB_PASSWORD: sip.2022
  DB_URL: jdbc:postgresql://sip-db-service.default.svc.cluster.local:5432/sip?user=sip&password=sip.2022
  SMTP_PASSWORD: xudijuocjkxwkgdo
  ADMIN_EMAIL: admin@admin.com
  ADMIN_PASSWORD: adminadmin
  APPLICATION_URL: http://34.75.130.221/