apiVersion: apps/v1
kind: Deployment
# create the namespace
metadata:
  name: sip-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sip-api
  template:
    metadata:
      labels:
        app: sip-api
    spec:
      containers:
        - name: app
          image: gcr.io/sip-unlu-2022/sip-api-image:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sip-api-configmap # Must match with API ConfigMap identifier


