apiVersion: apps/v1
kind: Deployment
# create the namespace
metadata:
  name: sip-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sip-api
  template:
    metadata:
      labels:
        app: sip-api
    spec:
      containers:
        - name: app
          image: gcr.io/sip-unlu-2022/sip-api-image:latest
          imagePullPolicy: Always
          env:
            - name: jwt-secret
              value: adminadmin
            - name: jwt-issuer
              value: SIP-2022
            - name: jwt-expiration-days
              value: "5"
