apiVersion: apps/v1
kind: Deployment
# create the namespace
metadata:
  name: sip-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sip-api
  template:
    metadata:
      labels:
        app: sip-api
    spec:
      containers:
        - name: app
          image: gcr.io/sip-unlu-2022/sip-api-image:latest
          imagePullPolicy: Always
          env:

            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: JWT_SECRET

            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: JWT_ISSUER

            - name: JWT_EXPIRATION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: JWT_EXPIRATION_DAYS

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: DB_NAME

            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: DB_PASSWORD

            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: DB_URL

            - name: SMTP_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: SMTP_PASSWORD

            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: ADMIN_EMAIL

            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sip-api-configmap
                  key: ADMIN_PASSWORD



