name: Build & Deploy to Google Kubernetes Engine

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  CONTAINER_IMAGE_NAME: ${{ secrets.GKE_CONTAINER_IMAGE_NAME }}
  DEPLOYMENT_NAME: ${{ secrets.GKE_CLUSTER_NAME }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Package
        run: mvn clean package -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      - name: Configure Docker for Google Cloud
        run: gcloud --quiet auth configure-docker

      - name: Log into GKE
        run: gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$CLUSTER_ZONE" --project "$PROJECT_ID"

      - name: Build Docker image
        run: docker build -t "gcr.io/$PROJECT_ID/$CONTAINER_IMAGE_NAME" .

      - name: Publish Docker image to GCR
        run: docker push "gcr.io/$PROJECT_ID/$CONTAINER_IMAGE_NAME"

      - name: Deploy to GKE
        run: |-
          kubectl apply -f kubernetes/api/deployment.yaml
          kubectl apply -f kubernetes/api/service.yaml
          kubectl get pods
          kubectl get services
