name: Build & Deploy to Google Kubernetes Engine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Package
        run: |-
          mvn clean package -DskipTests

      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$CLUSTER_ZONE"

      - name: Build Docker image
        run: docker build -t "gcr.io/$PROJECT_ID/$CONTAINER_IMAGE_NAME" .

      - name: Publish image to Google Container Registry
        run: docker push "gcr.io/$PROJECT_ID/$CONTAINER_IMAGE_NAME"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.5.5/kustomize_3.5.5_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy to GKE
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/CONTAINER_IMAGE_NAME=gcr.io/$PROJECT_ID/$CONTAINER_IMAGE_NAME
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
